In [1]:
import pandas as pd

In [2]:
# 시리즈 = pandas.Series(데이터)
# 데이터프레임 = pandas.DataFrame(데이터)

In [ ]:
# value의 길이는 반드시 같아야함
dict_data = {
    "c0": [1, 2, 3],
    "c1": [4, 5, 6],
    "c2": [7, 8, 9],
    "c3": [10, 11, 12],
    "c4": [13, 14, 15]
}

df = pd.DataFrame(dict_data)
print(type(df))
print(df)

<class 'pandas.DataFrame'>
   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [21]:
# 행 인데스 / 열 이름 설정
import pandas as pd

data = [
    [15, "남", "덕영중"],
    [17, "여", "수리중"],    
]

df = pd.DataFrame(data, index=["준서", "예은"], columns=["나이", "성별", "학교"])  # columns 없으면 인데스로 표시
print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [22]:
df

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [23]:
print(df.index)

Index(['준서', '예은'], dtype='str')

In [24]:
print(df.columns)

Index(['나이', '성별', '학교'], dtype='str')

In [25]:
df

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [26]:
df.index=["학생1", "학생2"]
df

     나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중

In [27]:
df.columns=["연령", "남녀", "소속"]
df

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [28]:
import pandas as pd

data = [
    [15, "남", "덕영중"],
    [17, "여", "수리중"],    
]

df = pd.DataFrame(data, index=["준서", "예은"], columns=["나이", "성별", "학교"])  # columns 없으면 인데스로 표시
print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [33]:
df = df.rename(columns={"나이":"연령", "성별":"남녀", "학교":"소속"}) # 재할당 안하면 원본은 안바뀜

In [34]:
df

    연령 남녀   소속
준서  15  남  덕영중
예은  17  여  수리중

In [36]:
df = df.rename(index={"준서":"학생1", "예은":"학생2"})
df

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [38]:
# 행/열 삭제
# 행삭제 - DataFrame객체.drop(행 인덱스 또는 배열, axis=0 또는 axis="index") # 기본적으로 axis는 행 삭제로 되어있음
# 열삭제 - DataFrame객체.drop(열 이름 또는 배열, axis=1 또는 axis="columns") # 행은 이름만으로도 찾기 가능
import pandas as pd

exam_data = {
    "수학": [90, 80, 70],
    "영어": [98, 89, 75],
    "음악": [85, 95, 100],
    "체육": [100, 90, 90]
}

df = pd.DataFrame(exam_data, index=["서준", "우현", "인아"])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  75  100   90

In [ ]:
df2 = df.copy()
df2 = df2.drop("우현") # 재할당 안하면 원본 안바뀜
df2

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  75  100   90

In [ ]:
df3 = df.copy()
df3 = df3.drop(["우현", "인아"], axis=0) # 재할당 안하면 원본 안바뀜
df3

    수학  영어  음악   체육
서준  90  98  85  100

In [44]:
df4 = df.copy()
df4 = df4.drop(["우현", "인아"], axis="index") # 재할당 안하면 원본 안바뀜
df4

    수학  영어  음악   체육
서준  90  98  85  100

In [45]:
df5 = df.copy()
df5 = df5.drop(index = ["우현"]) # 재할당 안하면 원본 안바뀜
df5

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  75  100   90

In [52]:
# 열 삭제
df2 = df.copy()
df2 = df2.drop("수학", axis=1)
df2

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  75  100   90

In [53]:
df3 = df.copy()
df3 = df3.drop(["영어", "음악"], axis=1)
df3

    수학   체육
서준  90  100
우현  80   90
인아  70   90

In [54]:
df4 = df.copy()
df4 = df4.drop(["영어", "음악"], axis="columns")
df4

    수학   체육
서준  90  100
우현  80   90
인아  70   90

In [55]:
df5 = df.copy()
df5 = df5.drop(columns=["수학"])
df5

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  75  100   90