In [13]:
import pandas as pd

df = pd.read_csv("./data/stock-data.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    20 non-null     str
 1   Close   20 non-null     int64
 2   Start   20 non-null     int64
 3   High    20 non-null     int64
 4   Low     20 non-null     int64
 5   Volume  20 non-null     int64
dtypes: int64(5), str(1)
memory usage: 1.1 KB

In [14]:
# 문자열을 Timestamp로 변환

df["Date"]

df["new_date"] = pd.to_datetime(df["Date"])
df["new_date"].head()
df["new_date"].info()

<class 'pandas.Series'>
RangeIndex: 20 entries, 0 to 19
Series name: new_date
Non-Null Count  Dtype
--------------  -----
20 non-null     datetime64[us]
dtypes: datetime64[us](1)
memory usage: 292.0 bytes

In [15]:
df = df.set_index("new_date")
df = df.drop("Date", axis=1)

df.head()

            Close  Start   High    Low  Volume
new_date
2018-07-02  10100  10850  10900  10000  137977
2018-06-29  10700  10550  10900   9990  170253
2018-06-28  10400  10900  10950  10150  155769
2018-06-27  10900  10800  11050  10500  133548
2018-06-26  10800  10900  11000  10700   63039

In [ ]:
pd.DatetimeIndex(
    "2022-12-15", "2023/01/25"  # 이 형태 아니면 컴퓨터가 인식 못함
)

In [16]:
pd.Timestamp("2023-12-25")

Timestamp('2023-12-25 00:00:00')

In [17]:
pd.Timestamp("2023/12/25")

Timestamp('2023-12-25 00:00:00')

In [19]:
pd.to_datetime("2025-12-25")

Timestamp('2025-12-25 00:00:00')

In [21]:
pd.to_datetime("2025년 12월 25일", format="%Y년 %m월 %d일")

Timestamp('2025-12-25 00:00:00')

In [22]:
pd.to_datetime("2025:12:25", format="%Y:%m:%d")

Timestamp('2025-12-25 00:00:00')

In [25]:
pd.to_datetime("12-12-2023 23:59:59")

Timestamp('2023-12-12 23:59:59')

In [ ]:
pd.to_datetime("5-12-2023 23:59:59", format="%d-%m-%Y %H:%M:%S")   # %m은 월, %M은 분

Timestamp('2023-12-05 23:59:59')

In [29]:
# timestamp를 이용해서 period로 변환

dates = ["2019-01-01", "2020-03-01", "2021-06-01"]

ts_dates = pd.to_datetime(dates)
ts_dates

DatetimeIndex(['2019-01-01', '2020-03-01', '2021-06-01'], dtype='datetime64[us]', freq=None)

In [30]:
pr_day = ts_dates.to_period(freq="D")
print(pr_day)
pr_month = ts_dates.to_period(freq="M")
print(pr_month)
pr_year = ts_dates.to_period(freq="Y")
print(pr_year)

PeriodIndex(['2019-01-01', '2020-03-01', '2021-06-01'], dtype='period[D]')
PeriodIndex(['2019-01', '2020-03', '2021-06'], dtype='period[M]')
PeriodIndex(['2019', '2020', '2021'], dtype='period[Y-DEC]')

In [33]:
# 시계열 데이터 만들기
ts_ms = pd.date_range(
    start="2024-01-01",
    end=None,
    periods=6,
    freq="MS",
    tz="Asia/Seoul"
)
ts_ms

DatetimeIndex(['2024-01-01 00:00:00+09:00', '2024-02-01 00:00:00+09:00',
               '2024-03-01 00:00:00+09:00', '2024-04-01 00:00:00+09:00',
               '2024-05-01 00:00:00+09:00', '2024-06-01 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='MS')

In [34]:
ts_me = pd.date_range(
    start="2024-01-01",
    end=None,
    periods=6,
    freq="ME",
    tz="Asia/Seoul"
)
ts_me

DatetimeIndex(['2024-01-31 00:00:00+09:00', '2024-02-29 00:00:00+09:00',
               '2024-03-31 00:00:00+09:00', '2024-04-30 00:00:00+09:00',
               '2024-05-31 00:00:00+09:00', '2024-06-30 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='ME')

In [35]:
ts_3m = pd.date_range(
    start="2024-01-01",
    periods=6,
    freq="3MS",
    tz="Asia/Seoul"
)
ts_3m

DatetimeIndex(['2024-01-01 00:00:00+09:00', '2024-04-01 00:00:00+09:00',
               '2024-07-01 00:00:00+09:00', '2024-10-01 00:00:00+09:00',
               '2025-01-01 00:00:00+09:00', '2025-04-01 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='3MS')

In [39]:
# 시계열 데이터 활용
df = pd.read_csv("./data/stock-data.csv")
df.head()

         Date  Close  Start   High    Low  Volume
0  2018-07-02  10100  10850  10900  10000  137977
1  2018-06-29  10700  10550  10900   9990  170253
2  2018-06-28  10400  10900  10950  10150  155769
3  2018-06-27  10900  10800  11050  10500  133548
4  2018-06-26  10800  10900  11000  10700   63039

In [40]:
df["new_Date"] = pd.to_datetime(df["Date"])
df.head()

         Date  Close  Start   High    Low  Volume   new_Date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26

In [42]:
df["year"] = df["new_Date"].dt.year

In [44]:
df["month"] = df["new_Date"].dt.month

In [45]:
df["day"] = df["new_Date"].dt.day

In [46]:
df.head()

         Date  Close  Start   High    Low  Volume   new_Date  year  month  day
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02  2018      7    2
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29  2018      6   29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28  2018      6   28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27  2018      6   27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26  2018      6   26

In [47]:
df["new_Date"].dt.to_period(freq="Y")

0     2018
1     2018
2     2018
3     2018
4     2018
5     2018
6     2018
7     2018
8     2018
9     2018
10    2018
11    2018
12    2018
13    2018
14    2018
15    2018
16    2018
17    2018
18    2018
19    2018
Name: new_Date, dtype: period[Y-DEC]

In [50]:
df["Date_yr"] = df["new_Date"].dt.to_period(freq="Y")
df["Date_m"] = df["new_Date"].dt.to_period(freq="M")
df.head()

,Date,Close,Start,High,Low,Volume,new_Date,year,month,day,Date_yr,Date_m
0,2018-07-02,10100,10850,10900,10000,137977,2018-07-02,2018,7,2,2018,2018-07
1,2018-06-29,10700,10550,10900,9990,170253,2018-06-29,2018,6,29,2018,2018-06
2,2018-06-28,10400,10900,10950,10150,155769,2018-06-28,2018,6,28,2018,2018-06
3,2018-06-27,10900,10800,11050,10500,133548,2018-06-27,2018,6,27,2018,2018-06
4,2018-06-26,10800,10900,11000,10700,63039,2018-06-26,2018,6,26,2018,2018-06

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      20 non-null     str
 1   Close     20 non-null     int64
 2   Start     20 non-null     int64
 3   High      20 non-null     int64
 4   Low       20 non-null     int64
 5   Volume    20 non-null     int64
 6   new_Date  20 non-null     datetime64[us]
 7   year      20 non-null     int32
 8   month     20 non-null     int32
 9   day       20 non-null     int32
 10  Date_yr   20 non-null     period[Y-DEC]
 11  Date_m    20 non-null     period[M]
dtypes: datetime64[us](1), int32(3), int64(5), period[M](1), period[Y-DEC](1), str(1)
memory usage: 1.8 KB

In [52]:
df_june = df[df['Date_m'].astype(str).str.fullmatch("2018-06")]
df_june.head()

,Date,Close,Start,High,Low,Volume,new_Date,year,month,day,Date_yr,Date_m
1,2018-06-29,10700,10550,10900,9990,170253,2018-06-29,2018,6,29,2018,2018-06
2,2018-06-28,10400,10900,10950,10150,155769,2018-06-28,2018,6,28,2018,2018-06
3,2018-06-27,10900,10800,11050,10500,133548,2018-06-27,2018,6,27,2018,2018-06
4,2018-06-26,10800,10900,11000,10700,63039,2018-06-26,2018,6,26,2018,2018-06
5,2018-06-25,11150,11400,11450,11000,55519,2018-06-25,2018,6,25,2018,2018-06

In [53]:
df_june2 = df[df['Date_m'] == pd.Period("2018-06")]
df_june2.head()

,Date,Close,Start,High,Low,Volume,new_Date,year,month,day,Date_yr,Date_m
1,2018-06-29,10700,10550,10900,9990,170253,2018-06-29,2018,6,29,2018,2018-06
2,2018-06-28,10400,10900,10950,10150,155769,2018-06-28,2018,6,28,2018,2018-06
3,2018-06-27,10900,10800,11050,10500,133548,2018-06-27,2018,6,27,2018,2018-06
4,2018-06-26,10800,10900,11000,10700,63039,2018-06-26,2018,6,26,2018,2018-06
5,2018-06-25,11150,11400,11450,11000,55519,2018-06-25,2018,6,25,2018,2018-06

In [55]:
# 시간 인덱스 활용
df = pd.read_csv("./data/stock-data.csv")
df["new_Date"] = pd.to_datetime(df["Date"])
df.head()

         Date  Close  Start   High    Low  Volume   new_Date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26

In [56]:
df = df.set_index("new_Date")
df.head()

                  Date  Close  Start   High    Low  Volume
new_Date
2018-07-02  2018-07-02  10100  10850  10900  10000  137977
2018-06-29  2018-06-29  10700  10550  10900   9990  170253
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-27  2018-06-27  10900  10800  11050  10500  133548
2018-06-26  2018-06-26  10800  10900  11000  10700   63039

In [59]:
df = df.sort_index()
df.head()

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-01  2018-06-01  11900  11800  12100  11750   32062
2018-06-04  2018-06-04  11900  11900  12200  11700   25171
2018-06-05  2018-06-05  12150  11800  12250  11800   42485
2018-06-07  2018-06-07  11950  12200  12300  11900   49088
2018-06-08  2018-06-08  11950  11950  12200  11800   59258

In [60]:
df.loc["2018-06-27"]

Date      2018-06-27
Close          10900
Start          10800
High           11050
Low            10500
Volume        133548
Name: 2018-06-27 00:00:00, dtype: object

In [62]:
df.loc["2018-06-27":"2018-07-02"]

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-27  2018-06-27  10900  10800  11050  10500  133548
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-29  2018-06-29  10700  10550  10900   9990  170253
2018-07-02  2018-07-02  10100  10850  10900  10000  137977

In [63]:
cond = df.index < "2018-06-05"
df[cond]

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-01  2018-06-01  11900  11800  12100  11750   32062
2018-06-04  2018-06-04  11900  11900  12200  11700   25171

In [65]:
pd.Timestamp("2018-06-27")

Timestamp('2018-06-27 00:00:00')

In [66]:
pd.Timestamp(2018, 6, 27)

Timestamp('2018-06-27 00:00:00')

In [67]:
df.loc[pd.Timestamp(2018,6,27): pd.Timestamp(2018,7,2)]

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-27  2018-06-27  10900  10800  11050  10500  133548
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-29  2018-06-29  10700  10550  10900   9990  170253
2018-07-02  2018-07-02  10100  10850  10900  10000  137977

In [69]:
pd.Timestamp(2018, 6, 27, 10, 30, 0)

Timestamp('2018-06-27 10:30:00')

In [70]:
df.loc[
    pd.Timestamp(2018, 6, 27, 10, 30, 0):pd.Timestamp(2018, 7, 2, 23, 59, 59)
]

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-29  2018-06-29  10700  10550  10900   9990  170253
2018-07-02  2018-07-02  10100  10850  10900  10000  137977

In [76]:
# timedelta
print(pd.Timedelta("1days"))
print(pd.Timedelta(days=1))
print(pd.Timedelta("1 days 1 hours 1 minutes 1 seconds"))
print(pd.Timedelta(days=1, hours=1, minutes=1, seconds=1))

1 days 00:00:00
1 days 00:00:00
1 days 01:01:01
1 days 01:01:01

In [77]:
pd.to_timedelta(["1 days", "3 hours"])

TimedeltaIndex(['1 days 00:00:00', '0 days 03:00:00'], dtype='timedelta64[us]', freq=None)

In [78]:
df.head(10)

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-01  2018-06-01  11900  11800  12100  11750   32062
2018-06-04  2018-06-04  11900  11900  12200  11700   25171
2018-06-05  2018-06-05  12150  11800  12250  11800   42485
2018-06-07  2018-06-07  11950  12200  12300  11900   49088
2018-06-08  2018-06-08  11950  11950  12200  11800   59258
2018-06-11  2018-06-11  11950  12000  12250  11950   62293
2018-06-12  2018-06-12  13200  12200  13300  12050  558148
2018-06-14  2018-06-14  13450  13200  13700  13150  347451
2018-06-15  2018-06-15  13400  13600  13600  12900  201376
2018-06-18  2018-06-18  12000  13400  13400  12000  309787

In [81]:
a = df.index

In [83]:
b = pd.Timestamp("2018-07-03") - a
b

TimedeltaIndex(['32 days', '29 days', '28 days', '26 days', '25 days',
                '22 days', '21 days', '19 days', '18 days', '15 days',
                '14 days', '13 days', '12 days', '11 days',  '8 days',
                 '7 days',  '6 days',  '5 days',  '4 days',  '1 days'],
               dtype='timedelta64[us]', name='new_Date', freq=None)

In [86]:
c = a + pd.Timedelta(days=1)

In [87]:
c.min()

Timestamp('2018-06-02 00:00:00')

In [88]:
c.max()

Timestamp('2018-07-03 00:00:00')

In [93]:
# 시계열 변환
df = pd.read_csv("./data/stock-data.csv")

df["new_Date"] = pd.to_datetime(df["Date"])

df = df.drop(columns=["Date"])
df = df.set_index("new_Date").sort_index()

ts = df.head(10)
ts

            Close  Start   High    Low  Volume
new_Date
2018-06-01  11900  11800  12100  11750   32062
2018-06-04  11900  11900  12200  11700   25171
2018-06-05  12150  11800  12250  11800   42485
2018-06-07  11950  12200  12300  11900   49088
2018-06-08  11950  11950  12200  11800   59258
2018-06-11  11950  12000  12250  11950   62293
2018-06-12  13200  12200  13300  12050  558148
2018-06-14  13450  13200  13700  13150  347451
2018-06-15  13400  13600  13600  12900  201376
2018-06-18  12000  13400  13400  12000  309787

In [94]:
ts.shift(1)

              Close    Start     High      Low    Volume
new_Date
2018-06-01      NaN      NaN      NaN      NaN       NaN
2018-06-04  11900.0  11800.0  12100.0  11750.0   32062.0
2018-06-05  11900.0  11900.0  12200.0  11700.0   25171.0
2018-06-07  12150.0  11800.0  12250.0  11800.0   42485.0
2018-06-08  11950.0  12200.0  12300.0  11900.0   49088.0
2018-06-11  11950.0  11950.0  12200.0  11800.0   59258.0
2018-06-12  11950.0  12000.0  12250.0  11950.0   62293.0
2018-06-14  13200.0  12200.0  13300.0  12050.0  558148.0
2018-06-15  13450.0  13200.0  13700.0  13150.0  347451.0
2018-06-18  13400.0  13600.0  13600.0  12900.0  201376.0

In [95]:
ts.shift(-2)

              Close    Start     High      Low    Volume
new_Date
2018-06-01  12150.0  11800.0  12250.0  11800.0   42485.0
2018-06-04  11950.0  12200.0  12300.0  11900.0   49088.0
2018-06-05  11950.0  11950.0  12200.0  11800.0   59258.0
2018-06-07  11950.0  12000.0  12250.0  11950.0   62293.0
2018-06-08  13200.0  12200.0  13300.0  12050.0  558148.0
2018-06-11  13450.0  13200.0  13700.0  13150.0  347451.0
2018-06-12  13400.0  13600.0  13600.0  12900.0  201376.0
2018-06-14  12000.0  13400.0  13400.0  12000.0  309787.0
2018-06-15      NaN      NaN      NaN      NaN       NaN
2018-06-18      NaN      NaN      NaN      NaN       NaN

In [96]:
ts.shift(3, freq="D")

            Close  Start   High    Low  Volume
new_Date
2018-06-04  11900  11800  12100  11750   32062
2018-06-07  11900  11900  12200  11700   25171
2018-06-08  12150  11800  12250  11800   42485
2018-06-10  11950  12200  12300  11900   49088
2018-06-11  11950  11950  12200  11800   59258
2018-06-14  11950  12000  12250  11950   62293
2018-06-15  13200  12200  13300  12050  558148
2018-06-17  13450  13200  13700  13150  347451
2018-06-18  13400  13600  13600  12900  201376
2018-06-21  12000  13400  13400  12000  309787