In [51]:
# 데이터 프레임
# {
#     '이름': ['김철수', '이영희', '박민수', '최지우'],
#     '나이': [20, 21, 22, 20],
#     '성별': ['남', '여', '남', '여'],
#     '수학': [90, 85, 70, 100],
#     '영어': [85, 95, 75, 90]
# }

# 1. df 라는 이름의 데이터프레임을 만들어 주세요
# 2. 생성된 데이터프레임의 상위 2개 행만 출력하세요.
# 3. 데이터프레임의 요약 정보(컬럼명, 데이터 타입 )을 확인하세요

# 4. '이름' 컬럼을 인덱스로 설정하세요. (기존 df를 수정)
# 5. loc을 사용하여 '이영희'의 '수학' 점수와 '영어' 점수만 추출하세요.
# 6. iloc을 사용하여 첫 번째 행부터 두 번째 행까지, 그리고 2번째 열(수학)부터 마지막 열까지 슬라이싱하세요.

# 시리즈
# {
#     '이름': ['김철수', '이영희', '박민수', '최지우'],
#     '나이': [20, 21, 22, 20],
#     '성별': ['남', '여', '남', '여'],
#     '수학': [90, 85, 70, 100],
#     '영어': [85, 95, 75, 90]
# }

# 1. 위 데이터로 시리즈 객체 sr을 만들어주세요
# 2. 시리즈의 인덱스 배열과 데이터값 배열을 각각 추출하여 화면에 출력하세요.

# list_data = ["2010-01-02", 3.14, "ABC", 100, True]
# 3. 위 데이터를 시리즈 객체로 만들어 주세요
# 4. 데이터 타입을 출력헤보세요

# tup_data = ("영인", "2010-05-01", "여", True)
# index_labels = ["이름", "생년월일", "성별", "학생여부"]
# 5. 위 데이터를 시리즈객체로 생성해주세요. 
# 6. 해당 시리즈의 원소 개수, 형상(shape), 차원을 출력해주세요 
# 7. 위치 기반(정수)으로 첫 번째 원소를 안전하게 조회하는 코드를 작성하세요. (iloc 활용)
# 8. 라벨 '이름'으로 원소를 조회하는 코드를 작성하세요.
# 9. 위치 인덱스 번호 리스트를 활용하여 '생년월일'과 '성별'을 가져오세요. (iloc 권장)
# 10. 라벨 이름 리스트를 활용하여 '생년월일'과 '성별'을 가져오세요.
# ---
# 11. 아무 데이터도 전달하지 않은 기본형 빈 시리즈를 생성하세요.
# 12. 스칼라 값 5와 인덱스 ["a", "b", "c"]를 사용하여 시리즈를 생성하고 출력하세요.

In [52]:
import pandas as pd

data_dict = {
    '이름': ['김철수', '이영희', '박민수', '최지우'],
    '나이': [20, 21, 22, 20],
    '성별': ['남', '여', '남', '여'],
    '수학': [90, 85, 70, 100],
    '영어': [85, 95, 75, 90]
}

# 1. df 라는 이름의 데이터프레임을 만들어 주세요
df = pd.DataFrame(data_dict)
df

    이름  나이 성별   수학  영어
0  김철수  20  남   90  85
1  이영희  21  여   85  95
2  박민수  22  남   70  75
3  최지우  20  여  100  90

In [53]:
# 2. 생성된 데이터프레임의 상위 2개 행만 출력하세요.
df.head(2)

    이름  나이 성별  수학  영어
0  김철수  20  남  90  85
1  이영희  21  여  85  95

In [71]:
# 3. 데이터프레임의 요약 정보(컬럼명, 데이터 타입 )을 확인하세요
print(df.index)
print(df.columns)
print(df.dtypes)

Index(['김철수', '이영희', '박민수', '최지우'], dtype='str', name='이름')
Index(['나이', '성별', '수학', '영어'], dtype='str')
나이    int64
성별      str
수학    int64
영어    int64
dtype: object

In [55]:
# 4. '이름' 컬럼을 인덱스로 설정하세요. (기존 df를 수정)
df = df.set_index("이름")
df

     나이 성별   수학  영어
이름
김철수  20  남   90  85
이영희  21  여   85  95
박민수  22  남   70  75
최지우  20  여  100  90

In [56]:
# 5. loc을 사용하여 '이영희'의 '수학' 점수와 '영어' 점수만 추출하세요.
df.loc["이영희", ["수학", "영어"]]

수학    85
영어    95
Name: 이영희, dtype: int64

In [57]:
# 6. iloc을 사용하여 첫 번째 행부터 두 번째 행까지, 그리고 2번째 열(수학)부터 마지막 열까지 슬라이싱하세요.
df.iloc[0:2,2:]

     수학  영어
이름
김철수  90  85
이영희  85  95

In [74]:
data_dict2 = {
    '이름': ['김철수', '이영희', '박민수', '최지우'],
    '나이': [20, 21, 22, 20],
    '성별': ['남', '여', '남', '여'],
    '수학': [90, 85, 70, 100],
    '영어': [85, 95, 75, 90]
}

# 1. 위 데이터로 시리즈 객체 sr을 만들어주세요
# 2. 시리즈의 인덱스 배열과 데이터값 배열을 각각 추출하여 화면에 출력하세요.

sr = pd.Series(data_dict2)
print(sr.index)
print(sr.values)

Index(['이름', '나이', '성별', '수학', '영어'], dtype='str')
[list(['김철수', '이영희', '박민수', '최지우']) list([20, 21, 22, 20])
 list(['남', '여', '남', '여']) list([90, 85, 70, 100]) list([85, 95, 75, 90])]

In [59]:
list_data = ["2010-01-02", 3.14, "ABC", 100, True]
# 3. 위 데이터를 시리즈 객체로 만들어 주세요
sr1 = pd.Series(list_data)
print(sr1)
# 4. 데이터 타입을 출력헤보세요
print()
print(sr1.dtype)

0    2010-01-02
1          3.14
2           ABC
3           100
4          True
dtype: object

object

In [60]:
tup_data = ("영인", "2010-05-01", "여", True)
index_labels = ["이름", "생년월일", "성별", "학생여부"]

# 5. 위 데이터를 시리즈객체로 생성해주세요. 
sr2 = pd.Series(tup_data, index=index_labels)
print(sr2)

이름              영인
생년월일    2010-05-01
성별               여
학생여부          True
dtype: object

In [61]:
# 6. 해당 시리즈의 원소 개수, 형상(shape), 차원을 출력해주세요 
print("원소 개수: ", len(sr2))
print("형성: ", sr2.shape)
print("차원: ", sr2.ndim)

원소 개수:  4
형성:  (4,)
차원:  1

In [62]:
# 7. 위치 기반(정수)으로 첫 번째 원소를 안전하게 조회하는 코드를 작성하세요. (iloc 활용)
sr2.iloc[0]

'영인'

In [63]:
# 8. 라벨 '이름'으로 원소를 조회하는 코드를 작성하세요.
print(sr2.loc["이름"])
print(sr2["이름"])

영인
영인

In [64]:
# 9. 위치 인덱스 번호 리스트를 활용하여 '생년월일'과 '성별'을 가져오세요. (iloc 권장)
sr2.iloc[1:3]

생년월일    2010-05-01
성별               여
dtype: object

In [65]:
# 10. 라벨 이름 리스트를 활용하여 '생년월일'과 '성별'을 가져오세요.
sr2.loc[["생년월일","성별"]]

생년월일    2010-05-01
성별               여
dtype: object

In [66]:
# 11. 아무 데이터도 전달하지 않은 기본형 빈 시리즈를 생성하세요.

sr3 = pd.Series()
sr3

Series([], dtype: object)

In [67]:
# 12. 스칼라 값 5와 인덱스 ["a", "b", "c"]를 사용하여 시리즈를 생성하고 출력하세요.
sr4 = pd.Series(5, index=["a", "b", "c"])
sr4

a    5
b    5
c    5
dtype: int64